import {expect,test} from '@playwright/test';
import {addMaterial} from '../../src/sim/materials.ts';
import {serializeWorld,validateWorld} from '../../src/sim/serialization.ts';
import {mentalCamp} from '../scenarios/mental-break.ts';
import {expectWorld,observeErrors,panel,pawnTab,saveKey,world} from './helpers.ts';

test('V150 food binge: confirmed entry, physical meal, inspection and saved replay',async({page})=>{
  test.setTimeout(120000);
  const initial=mentalCamp(1),pawn=initial.pawns[0]!;
  pawn.rest=90;pawn.hunger=98;pawn.foodPolicyId=4;
  addMaterial(initial,'food',40,{type:'ground',x:pawn.x+2,z:pawn.z},'rice');
  const initialFood=initial.piles.filter(p=>p.kind==='food').reduce((sum,p)=>sum+p.quantity,0);
  const errors=observeErrors(page);
  await page.addInitScript(({key,data})=>localStorage.setItem(key,data),{key:saveKey,data:serializeWorld(initial)});
  await page.goto('/?scenario=camp&e2e&size=32');
  await expect(page.locator('#loading')).toHaveCount(0);
  await page.locator('[data-speed="0"]').click();
  await panel(page,'menu');await page.locator('#load').click();await expectWorld(page,initial);await page.keyboard.press('Escape');
  await page.locator('[data-speed="6"]').click();
  await expect.poll(async()=>(await world(page)).pawns[0]!.mental?.crisis?.kind,{timeout:30000,intervals:[100]}).toBe('food-binge');
  await page.locator('[data-speed="0"]').click();
  await page.locator(`[data-pawn="${pawn.id}"]`).click();
  await expect(page.locator('#alerts')).toContainText('frénésie alimentaire');
  await pawnTab(page,'needs');
  await expect(page.locator('#mood-target')).toContainText('Frénésie alimentaire');
  await expect(page.locator('#toggle-draft')).toBeDisabled();
  await page.locator('[data-speed="6"]').click();
  await expect.poll(async()=> (await world(page)).events.some(e=>e.message.includes('a mangé une portion')),{timeout:45000,intervals:[150]}).toBe(true);
  await page.locator('[data-speed="0"]').click();
  const eating=await world(page);
  expect(eating.pawns[0]!.mental?.crisis?.kind).toBe('food-binge');
  expect(eating.piles.filter(p=>p.kind==='food').reduce((sum,p)=>sum+p.quantity,0)).toBeLessThan(initialFood);
  expect(validateWorld(eating)).toEqual([]);
  await panel(page,'menu');await page.locator('#save').click();await page.locator('#load').click();
  await expectWorld(page,eating);await page.keyboard.press('Escape');
  expect(errors).toEqual([]);
});
