import { test, expect } from '@playwright/test';
import { miningCamp } from '../scenarios/mining';
import { serializeWorld, validateWorld } from '../../src/sim/index';
import { cell, tool, panel, saveKey, world, expectWorld, observeErrors } from './helpers';
import { revealCells } from './player-actions';

test('miner, reprendre la roche endommagée et ranger son fragment par les commandes visibles',async({playwright},testInfo)=>{
  const browser=await playwright.chromium.launch({channel:'chromium',args:[]});
  const page=await browser.newPage({baseURL:'http://127.0.0.1:5173',viewport:{width:1440,height:1000}});page.setDefaultTimeout(10000);
  const errors=observeErrors(page);
  try {
    const fixture=miningCamp(),target={x:13,z:14},index=target.z*32+target.x;fixture.tiles[index]={terrain:'rock',stone:'granite'};fixture.rng=1;fixture.tiles[11*32+12]={terrain:'rock',stone:'granite',ore:'steel'};fixture.tiles[11*32+14]={terrain:'rock',stone:'slate',ore:'machinery'};
    await page.addInitScript(({key,saved})=>localStorage.setItem(key,saved),{key:saveKey,saved:serializeWorld(fixture)});
    await page.goto('/?scenario=camp&e2e');await expect(page.locator('#loading')).toHaveCount(0);await page.locator('[data-speed="0"]').click();
    await panel(page,'menu');await page.locator('#load').click();await expectWorld(page,fixture);await page.keyboard.press('Escape');
    await expect(page.locator('#fps-counter')).toBeVisible();
    await panel(page,'work');await page.locator('select[data-work="mine"]').selectOption('1');
    await tool(page,'mine');await revealCells(page,[target]);await cell(page,target.x,target.z);await page.keyboard.press('Escape');
    await page.locator('[data-speed="6"]').click();
    await page.waitForFunction(i=>{const w=window.__lisiere.world;if((w.tiles[i]!.miningDamage??0)>=160){(document.querySelector('[data-speed="0"]') as HTMLButtonElement).click();return true;}return false;},index,{polling:50});
    await expect(page.locator('#pause-banner')).toBeVisible();const damaged=await world(page);expect(damaged.tiles[index]!.terrain).toBe('rock');
    await panel(page,'menu');await page.locator('#save').click();await page.locator('#load').click();await expectWorld(page,damaged);await page.keyboard.press('Escape');
    await page.locator('[data-speed="6"]').click();await page.waitForFunction(i=>{if(window.__lisiere.world.tiles[i]!.terrain==='rough-stone'){(document.querySelector('[data-speed="0"]') as HTMLButtonElement).click();return true;}return false;},index,{polling:50});
    await expect(page.locator('#pause-banner')).toBeVisible();let current=await world(page);expect(current.piles).toHaveLength(1);expect(current.piles[0]!.item).toBe('granite-chunk');
    await tool(page,'stockpile');await page.locator('#stockpile-wood').uncheck();await page.locator('#stockpile-food').uncheck();await page.locator('#stockpile-chunk').check();
    await revealCells(page,[{x:19,z:16}]);await cell(page,19,16);await page.keyboard.press('Escape');
    const tick=current.tick;await page.locator('[data-speed="6"]').click();await page.waitForFunction(t=>window.__lisiere.tick>=t,tick+30);await page.locator('[data-speed="0"]').click();
    current=await world(page);expect(current.piles[0]!.owner).toEqual({type:'ground',...target});
    await tool(page,'haul-chunks');await revealCells(page,[target]);await cell(page,target.x,target.z);await page.keyboard.press('Escape');await page.locator('[data-speed="6"]').click();
    await page.waitForFunction(()=>{const w=window.__lisiere.world;return w.piles.length===1&&w.piles[0]!.owner.type==='ground'&&w.piles[0]!.owner.x===19;},undefined,{polling:100});await page.locator('[data-speed="0"]').click();
    current=await world(page);expect(validateWorld(current)).toEqual([]);expect(current.piles[0]).toMatchObject({item:'granite-chunk',quantity:1,owner:{type:'ground',x:19,z:16}});
    await panel(page,'menu');await page.locator('#save').click();await page.locator('#load').click();await expectWorld(page,current);await page.keyboard.press('Escape');
    await page.screenshot({path:'artifacts/mining-ui.png'});
    await tool(page,'mine');await revealCells(page,[{x:12,z:11}]);await cell(page,12,11);await page.keyboard.press('Escape');
    await page.locator('[data-speed="6"]').click();await page.waitForFunction(()=>window.__lisiere.world.tiles[11*32+12]!.terrain==='rough-stone');await page.locator('[data-speed="0"]').click();
    await expect(page.locator('#steel')).toHaveText('40');
    await tool(page,'stockpile');await page.locator('#stockpile-chunk').uncheck();await page.locator('#stockpile-steel').check();await revealCells(page,[{x:19,z:17}]);await cell(page,19,17);await page.keyboard.press('Escape');
    await page.locator('[data-speed="6"]').click();await page.waitForFunction(()=>{const w=window.__lisiere.world;return w.piles.some(p=>p.item==='steel'&&p.quantity===40&&p.owner.type==='ground'&&p.owner.x===19&&p.owner.z===17);});await page.locator('[data-speed="0"]').click();
    current=await world(page);expect(validateWorld(current)).toEqual([]);expect(current.piles.filter(p=>p.item==='steel')).toHaveLength(1);
    await panel(page,'menu');await page.locator('#save').click();await page.locator('#load').click();await expectWorld(page,current);await page.keyboard.press('Escape');
    await page.screenshot({path:'artifacts/steel-ui.png'});
    await revealCells(page,[{x:14,z:11}]);await cell(page,14,11);
    await expect(page.locator('#cell-description')).toContainText('2000 / 2000 PV');
    await page.screenshot({path:'artifacts/components-deposit-ui.png'});
    await tool(page,'mine');await cell(page,14,11);await page.keyboard.press('Escape');
    await page.locator('[data-speed="6"]').click();
    await page.waitForFunction(()=>{const w=window.__lisiere.world;if((w.tiles[11*32+14]!.miningDamage??0)>=80){(document.querySelector('[data-speed="0"]') as HTMLButtonElement).click();return true;}return false;},undefined,{polling:30});
    current=await world(page);expect(current.tiles[11*32+14]!.terrain).toBe('rock');expect(current.piles.some(p=>p.item==='component')).toBe(false);
    expect(current.pawns.some(p=>p.state==='working')).toBe(true);
    await page.locator('[data-speed="6"]').click();await page.waitForFunction(()=>window.__lisiere.world.tiles[11*32+14]!.terrain==='rough-stone');await page.locator('[data-speed="0"]').click();
    await expect(page.locator('#component')).toHaveText('2');
    await tool(page,'stockpile');await page.locator('#stockpile-steel').uncheck();await page.locator('#stockpile-component').check();await revealCells(page,[{x:19,z:18}]);await cell(page,19,18);await page.keyboard.press('Escape');
    await page.locator('[data-speed="6"]').click();await page.waitForFunction(()=>window.__lisiere.world.piles.some(p=>p.item==='component'&&p.owner.type==='pawn'),undefined,{polling:20});
    await page.screenshot({path:'artifacts/components-carried-ui.png'});
    await page.waitForFunction(()=>window.__lisiere.world.piles.some(p=>p.item==='component'&&p.quantity===2&&p.owner.type==='ground'&&p.owner.x===19&&p.owner.z===18));await page.locator('[data-speed="0"]').click();
    current=await world(page);expect(validateWorld(current)).toEqual([]);
    await panel(page,'menu');await page.locator('#save').click();await page.locator('#load').click();await expectWorld(page,current);await page.keyboard.press('Escape');
    await page.screenshot({path:'artifacts/components-stored-ui.png'});expect(errors).toEqual([]);await testInfo.attach('mining-outcome',{body:JSON.stringify({tile:current.tiles[index],piles:current.piles,errors}),contentType:'application/json'});
  }finally{await browser.close();}
});
